CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY
	,Username NVARCHAR(50) NOT NULL
	,EnemiesKilled INT NOT NULL
	,DamageDealt DECIMAL(18,3) NOT NULL	
	,GamePoints DECIMAL(18,3) NOT NULL
	,WeaponId INT FOREIGN KEY REFERENCES Weapons(Id)
	,MapId INT FOREIGN KEY REFERENCES Maps(Id)
)
CREATE TABLE Weapons
(
	Id INT PRIMARY KEY IDENTITY
	,[Name] NVARCHAR(15) NOT NULL
	,AmmoType DECIMAL(18,2) NOT NULL
	,[Power] DECIMAL(18,2) NOT NULL
	,Damage DECIMAL(18,2) NOT NULL
	,HeadShot BIT NOT NULL
	
)
CREATE TABLE Enemies
(
	Id INT PRIMARY KEY IDENTITY
	,[Name] NVARCHAR(15) NOT NULL
	,Size INT NOT NULL
	,Health DECIMAL(18,2) NOT NULL
	,Life DECIMAL(18,2) NOT NULL
	,IsRegenerated BIT NOT NULL
)
CREATE TABLE Maps
(
	Id INT PRIMARY KEY IDENTITY
	,X INT NOT NULL
	,Y INT NOT NULL
	,Terrain NVARCHAR(20) NOT NULL
)
CREATE TABLE UsersEnemies
(
--composite key needed for users who kill more than 1 enemy
	UserId INT FOREIGN KEY REFERENCES Users(Id)
	,EnemyId INT FOREIGN KEY REFERENCES Enemies(Id)
	PRIMARY KEY(UserId,EnemyId)
)
